namespace GalaxyBudsClient.Model.Specifications;

public enum Features
{
    SeamlessConnection,
    AmbientExtraLoud,
    AmbientVoiceFocus,
    AmbientSidetone,
    AmbientPassthrough,
    AmbientSound,
    Anc,
    NoiseControl,
    BixbyWakeup,
    DetectConversations,
    GamingMode,
    DoubleTapVolume,
    CaseBattery,
    BatteryType,
    Voltage,
    Current,
    FragmentedMessages,
    StereoPan,
    FirmwareUpdates,
    SpatialSensor,
    AmbientCustomize,
    AmbientCustomizeLegacy,
    AncWithOneEarbud,
    AncNoiseReductionLevels,
    AdvancedTouchLock,
    AdvancedTouchLockForCalls,
    FmgRingWhileWearing,
    LegacyAmbientSoundVolumeLevels,
    BuildInfo,
    GearFitTest,
    DebugSku
}
